service:
  name: aws-sns-sqs-lambda-trigger-template
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - sqs:
          arn: your-sqs-arn
          batchSize: your lambda batch size
